### ISSUE TITLE
Ability to configure type of brackets

### ISSUE THREAD

**Issue by gesundes** [nemwiz/jira-commit-message-intellij-plugin#3]
I love this plugin! But I have a small request.

For now, the plugin generates something like `(PROJECT-123)`, i.e. uses standard brackets.
But different teams have different standards. Some guys use square brackets [] and some use curly ones {}.
It will be great if it will be possible to configure it in preferences.

Thank you!

**Comment by nemwiz** [comment]
@gesundes Sounds like a reasonable feature. I will add this in upcoming release and make it configurable.
