### ISSUE TITLE
Option of empty wrapper

### ISSUE THREAD

**Issue by moreorover** [nemwiz/jira-commit-message-intellij-plugin#49]
Would it be possible to have have an option available for an empty wrapper? Something that looks like this:

Current examples:
(FROG-1234)
{FROG-1234}

What I'm looking for is just have no wrapper.
FROG-1234

**Comment by nemwiz** [comment]
Great suggestion, this option is definitely lacking. Give me some time, it will be added soon. 👍

**Comment by nemwiz** [comment]
@moreorover Version 2.2.0 with the `No wrapper` option has just been published. If you enjoy using this plugin, please support us by [leaving a review or rating](https://plugins.jetbrains.com/plugin/14310-jira-id-commit-message)
