### ISSUE TITLE
Add option for infix

### ISSUE THREAD

**Issue by thijmenketel** [nemwiz/jira-commit-message-intellij-plugin#57]
I would like to have an option to automatically add an infix between the prefix and the commit message.

Ex.
* Prefix: TICKET-1234
* Wrap: []
* Infix: -

Would result in:
* [TICKET-1234] -

**Comment by nemwiz** [comment]
Something similar was requested already and I provided my reasoning [in this issue](https://github.com/nemwiz/jira-commit-message-intellij-plugin/pull/4)

Give me some time to think about this. As explained in the other issue, the main goal of this plugin is to be simple. Let me think how can I provide this functionality in a simple manner (e.g. no regex).

Do you have any suggestions?

**Comment by thijmenketel** [comment]
I would actually keep it simple.

When I look at the code in [MyProjectService.kt](https://github.com/nemwiz/jira-commit-message-intellij-plugin/blob/main/src/main/kotlin/org/nemwiz/jiracommitmessage/services/MyProjectService.kt#L58) in the method on line 58 you could just add a an extra parameter to the String format.

Even allowing a space between the infix if you'd like.

**Comment by nemwiz** [comment]
I agree, but my question was more on how to specify the infix e.g. I'd like something similar that is available now for brackets. It's a dropdown with all the possible brackets. With the infix, it becomes a bit more difficult for example:
- You need to choose the infix
- Some folks would want a space before the infix
- Some folks would want a space after the infix
- Some don't want spaces at all
- etc.

Any suggestion on how to make this easily configurable is appreciated.

**Comment by nemwiz** [comment]
@thijmenketel I've added this feature in the most simple way possible. Would you be so kind to test it out? 
I've also implemented https://github.com/nemwiz/jira-commit-message-intellij-plugin/issues/56 
You can install this version by going to Plugins -> Click the cog icon -> Install plugin from disk

[jira-commit-message-3.1.0.zip](https://github.com/nemwiz/jira-commit-message-intellij-plugin/files/10387133/jira-commit-message-3.1.0.zip)

Thanks

**Comment by thijmenketel** [comment]
I will take a look

**Comment by thijmenketel** [comment]
The infix option works like a charm!

**Comment by nemwiz** [comment]
Awesome. I'll release the new version now and close this issue.
