### ISSUE TITLE
Add prefix to ticket id

### ISSUE THREAD

**Issue by wawyed** [nemwiz/jira-commit-message-intellij-plugin#68]
We use the convention `#JIRA_TICKET_ID ...`.

It would be awesome to be able to define such prefix as #.

**Comment by nemwiz** [comment]
@wawyed 
I've implemented this feature in the latest version. Could you test it out? Let me know if you encounter any issues.

You can install this version by going to Plugins -> Click the cog icon -> Install plugin from disk
[jira-commit-message-3.3.0.zip](https://github.com/nemwiz/jira-commit-message-intellij-plugin/files/11564541/jira-commit-message-3.3.0.zip)


Thanks

**Comment by nemwiz** [comment]
This feature has been released in [v3.3.0](https://github.com/nemwiz/jira-commit-message-intellij-plugin/releases/tag/v3.3.0)
Please leave [a review](https://plugins.jetbrains.com/plugin/14310-jira-id-commit-message) if you find this plugin useful. Thanks!

**Comment by wawyed** [comment]
Thank you :D
