### ISSUE TITLE
Prefixes commit message with "test" if it exists in branch name

### ISSUE THREAD

**Issue by mbrewerton** [nemwiz/jira-commit-message-intellij-plugin#71]
**Describe the bug**
Whenever I create a branch with `test` in the branch name, the commit message is always prefixed with `test`.

For example if I create a branch `TICK-123-feature-branch-name` it will set the commit message correctly as `TICK-123 -` as per my settings.

If I create a branch `TICK-123-feature-test-branch-name` or `TICK-123_feature-test-branch-name` it will set the commit message **incorrectly** to `testTICK-123 -`.

**"test" seems to be the only word to cause this behaviour.**

**To Reproduce**
1. Create a branch with "test" in the name.
2. Click the **Commit Message Id button** or let it autogenerate
3. Observe incorrect prefix

**Expected behavior**
Only prefix with the Jira ticket id as described by the plugin.

**Screenshots**
Branch name:
![image](https://github.com/nemwiz/jira-commit-message-intellij-plugin/assets/10398455/e42012f7-0197-41d1-848b-b4e7975158df)

Generated commit message:
![image](https://github.com/nemwiz/jira-commit-message-intellij-plugin/assets/10398455/6f9cac65-d515-44b9-a6ff-5633bb768c39)

**System version (please complete the following information):**
 - PhpStorm 2023.1.1
   - Build #PS-231.8770.68
 - Plugin version: 3.3.0
 - OS: Windows 10

**Comment by nemwiz** [comment]
Thanks for reporting this.
Just to confirm, you are using [Automatically detect JIRA project key option](https://github.com/nemwiz/jira-commit-message-intellij-plugin#automatic)?
Would be great if you can share the full plugin configuration, especially if the `Conventional commits` feature is on.

Thanks

**Comment by mbrewerton** [comment]
Hi, I am using that setting, here's what my settings look like:
![image](https://github.com/nemwiz/jira-commit-message-intellij-plugin/assets/10398455/67e8f7be-d335-4ab2-9642-c6d25ecceb57)

I've found this morning that it's also doing it with the word "fix". I have a branch name `TICKET-123-account-rename-fix` and it's setting the commit prefix to `fixTICKET-123 -`.

**Comment by nemwiz** [comment]
@mbrewerton Yes, I'm not surprised by this behaviour because you have the `Automatically detect conventional commits` option on. It's kind of a bug because I should probably standardize this and only allow e.g. `test` to show up in the commit if the branch name starts with `test` rather than this keyword being in the middle of the branch name.

Either way, to solve your problem - if you project is not using [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), please turn off this option in the settings and everything should work as expected.

Thanks

**Comment by nemwiz** [comment]
I've just released the latest version which tackles this issue. To summarize the changes:

For folks who are not using conventional commits -> turn off this functionality.
For folks who are using conventional commits -> your branch has to start with one of the keywords e.g. `test/my-feature-PROJ-123` or `feat/PROJ-456`. Having these keywords in the middle of the branch will not work anymore.
