### ISSUE TITLE
JIRA task id is not appended to the commit message, neither frog button works

### ISSUE THREAD

**Issue by jolice** [nemwiz/jira-commit-message-intellij-plugin#72]
**Describe the bug**
Commit message is not appended

**To Reproduce**
1. Switch to branch: in my case, **f/LGP-357/somefeature**
2. Click commit
3. Jira id is not appended. Commit message field is just empty. Clicking on a Frog button also does nothing.

**Expected behavior**

Jira ID is appended correctly.

**Screenshots**

![image](https://github.com/nemwiz/jira-commit-message-intellij-plugin/assets/25826296/13870ce3-b9f1-4103-b1d7-5fdffb0ab4ee)
![image](https://github.com/nemwiz/jira-commit-message-intellij-plugin/assets/25826296/b75d805d-5d83-43c8-8258-a371bb02c3d2)

**System version (please complete the following information):**
 - IntelliJ version: 2021.3.1
 - Plugin version: 3.2.0
 - OS: Windows

**Additional context**

Seems like a heisenbug, appears randomly on some projects. Still, I haven't found any correlation between branch name .

**Comment by nemwiz** [comment]
There was a [similar bug reported](https://github.com/nemwiz/jira-commit-message-intellij-plugin/issues/67) but I wasn't able to reproduce it.

Is your project open source? I will try with the branch name that you've provided and see if I can reproduce.

I would also suggest updating the plugin to the latest version 3.30 and see if it appears there.

Last resort would be for you to checkout this repo, run the plugin locally and debug it.

**Comment by jolice** [comment]
Hello,

Unfortunately this an enterprise project. I tried different branch names but it's all the same, I think the problem is not related to the name of the branch. 

I also can't update a plugin because I run IDE 2021.3.1 (can't update due to certain reasons).

**Comment by nemwiz** [comment]
@jolice Is this bug still appearing? Not sure if anything changed on your end. It's difficult to reproduce this because of an older version of IntelliJ.
The latest version of the plugin has been improved with logging. If you can run that version, you should be able to see if any errors are happening.

**Comment by jolice** [comment]
@nemwiz hi,

Unfortunately I'm not able to upgrade Intellij due to licensing limitations, so the bug still takes place. Anyway, I hope it doesn't appear in the newer versions.
