### ISSUE TITLE
Custom prefix and infix settings

### ISSUE THREAD

**Issue by stevehogdahl** [nemwiz/jira-commit-message-intellij-plugin#80]
I have a couple settings feature requests/suggestions.

Can we have custom infix/prefix settings? I usually just put a space at the end and there's no way to do that with the current settings.

Semi related, what are your thoughts on making the selecting of the commit message configurable? I have no use for selecting the commit message after it's inputed. It's just an extra step i have to take to start typing the rest of the message.

**Comment by nemwiz** [comment]
Support for custom infix/prefix was asked before and I've elaborated the reasons for not providing this feature in a [different issue](https://github.com/nemwiz/jira-commit-message-intellij-plugin/pull/4).

If you can provide me with a few examples of your commit messages, I can think of extending the current list of prefixes, but keeping things simple is still a priority of this plugin.

For your second point, I fully agree with you. The selection is very annoying but this is sadly done by the IntelliJ under the hood. Last time I checked, there was no way of turning off this behavior. It's been a while though so I'll have a look again at their API to see if things have changed.

**Comment by stevehogdahl** [comment]
I just want a space after the infix, even if it's after the current list of infixes. I actually used to use the plugin you linked in the other issue, but it's not supported in the new version of intellij.

That's a bummer, thanks for letting me know though.

**Comment by nemwiz** [comment]
I think it's a fair ask. When I think about the plugin usage, majority of folks will add a space after their infix in order to write the actual commit message. It might make sense to make this a default behavior and that the space is always added.

However, I feel that this is something that shouldn't be configurable, the plugin already has too many options and this one seems not so relevant for it to be configurable, after all it's just a single keypress.

Let me try it out and look at the selection issue as well.

**Comment by stevehogdahl** [comment]
Sounds good, thank you!

**Comment by nemwiz** [comment]
Every message should have a space at the end now. 
Could you test it out? You can install this version by going to Plugins -> Click the cog icon -> Install plugin from disk

[jira-commit-message-3.4.2.zip](https://github.com/nemwiz/jira-commit-message-intellij-plugin/files/14106413/jira-commit-message-3.4.2.zip)

I've [asked about the text selection](https://intellij-support.jetbrains.com/hc/en-us/community/posts/16398114076434-Removing-text-selection-for-commit-message) and as expected, things haven't changed there. All these proposals are hacky and unreliable so I can't remove the text selection.

**Comment by stevehogdahl** [comment]
That works for me, thanks for asking about the text selection also
