### ISSUE TITLE
Allow a keyboard shortcut to populate the commit message

### ISSUE THREAD

**Issue by nikhilpatil** [nemwiz/jira-commit-message-intellij-plugin#84]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but when I'm in the commit message window, I'm usually working with only the keyboard.

**Describe the solution you'd like**
A pre-defined keyboard shortcut to populate the message automatically. Or, a configurable shortcut via the settings.

**Describe alternatives you've considered**
Alternative is obviously clicking on the frog action button - it does the same thing but I have to click on it with a mouse.

Thank you for this plugin!

**Comment by nemwiz** [comment]
This should already be supported. 
If you go to `Settings -> Version Control -> Commit -> Use non modal commit interface` - is this option on or off?

1. In case it's on, open `Settings -> Keymaps -> Plugins -> Jira id commit message` and assign your shortcut.
2. In case it's off, every time you want to commit a modal window will show up and the message will be populated automatically

Let me know if that worked.

**Comment by nikhilpatil** [comment]
@nemwiz apologies for the late response. You are absolutely right. This works perfectly! Would you consider adding this to the readme? This seems like very useful knowledge. I'll also be happy to raise a PR :)
